version: "3"

services:
  db:
    image: mysql:5.7
    container_name: db
    restart: always
    tty: true
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: nodedb
      MYSQL_ROOT_PASSWORD: root
    networks:
      - node-network

  app:
    build: ./node
    command: dockerize -wait tcp://db:3306 -timeout 20s sh -c "npm install && node index.js"
    container_name: app
    restart: always
    tty: true
    ports:
      - "3000:3000"
    depends_on:
      - db
    volumes:
      - ./node:/usr/src/app
    networks:
      - node-network

  nginx:
    image: nginx:latest
    container_name: nginx
    restart: on-failure
    tty: true
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app
    networks:
      - node-network

networks:
  node-network:
    driver: bridge
